### ISSUE TITLE
write a documentation on APIs and Postman

### ISSUE THREAD

**Issue by ShaileshKumar007** [GDSC-CEC/HacktoberFest-2022-Technical-Documentation#11]
Write documentation on API and Postman.
Your documentation should cover the different concepts of Postman and API

**Comment by ShaileshKumar007** [comment]
> Please assign me on this

Great. I'm assigning this issue to you.
Please make sure to mention this issue while making a PR

**Comment by Pragya2056** [comment]
Does both API and Postman need to be in the same file or can we do different ?
@ShaileshKumar007

**Comment by ShaileshKumar007** [comment]
Your PR has already been merged. That's why I'm closing this issue
